packages:
  - packages/*
  - docs

catalog:
  '@sveltejs/kit': ^2.42.1
  '@sveltejs/vite-plugin-svelte': ^6.2.0
  '@tailwindcss/vite': ^4.1.13
  '@types/node': ^22.18.5
  svelte: ^5.38.10
  svelte-check: ^4.3.1
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vite: ^7.1.5

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@sveltejs/kit'
  - '@tailwindcss/oxide'
  - esbuild
  - workerd
